# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Release extension

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Use Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: "npm"
      - run: npm ci
      - run: npm run package -- ${{  github.ref_name }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ng-lint-ast-viewer-*.vsix
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
      - name: Publish to microsoft marketplace
        run: npm run deploy:ms
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
      - name: Publish to eclipse marketplace
        run: npm run deploy:eclipse -- -p ${{ secrets.OPEN_VSX_PAT }}
